import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import { useAuth } from "../hooks/auth";

const Home: NextPage = () => {
  const { data, error, register } = useAuth();
  if (error) return <div>fail to load</div>;
  if (!data) return <div>loading...</div>;
  return (
    <div className={styles.container}>
      <Head>
        <title>TMT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Main</main>

      {data.map((user: any, index: any) => (
        <div key={index}>{user.email}</div>
      ))}
      <button
        onClick={() =>
          register({ email: "admin@gmail.com", password: "123456" })
        }
      >
        Register
      </button>
    </div>
  );
};

export default Home;
